substitutions:
  dimmer_bindkey: !secret dimmer_bindkey
  dimmer_mac_address: !secret dimmer_mac_address

# --------------------------------------------------------------------------
# Load packages firmware packages -- adjust to your own liking
# core.yaml should always be included
# --------------------------------------------------------------------------

packages:
  - !include packages/core.yaml
  - !include packages/blinking-service.yaml
  - !include packages/generated-preset-select.yaml

# --------------------------------------------------------------------------
# Use your own values below to set up network, api access and ota password
# --------------------------------------------------------------------------

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
  encryption:
    key: !secret api_encryption_key

ota:
  platform: esphome
  password: !secret ota_password