substitutions:
  dimmer_bindkey: !secret dimmer_bindkey
  dimmer_mac_address: !secret dimmer_mac_address

# --------------------------------------------------------------------------
# Load extractor package
# --------------------------------------------------------------------------

packages:
  - !include packages/core.yaml

# --------------------------------------------------------------------------
# Use your own values to set up networking
# --------------------------------------------------------------------------

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
  encryption:
    key: !secret api_encryption_key
  # Lamp is a lamp after all, no need to reboot if Home Assistant is not available
  reboot_timeout: 0s

ota:
  platform: esphome
  password: !secret ota_password